### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by xyproto** [fragata-ai/arhat#1]
I'm trying to run an example that uses the CPU.

After cloning the repository, I tried running:

    mkdir -p bin
    mkdir -p mnist_mlp_cpu
    go build -o bin/mnist_mlp_cpu fragata/arhat/examples/mnist_mlp_cpu

This gives the error message:

```
can't load package: package fragata/arhat/examples/mnist_mlp_cpu: cannot find package "fragata/arhat/examples/mnist_mlp_cpu" in any of:
/usr/lib/go/src/fragata/arhat/examples/mnist_mlp_cpu (from$GOROOT)
/home/afr/go/src/fragata/arhat/examples/mnist_mlp_cpu (from $GOPATH)
```

Thinking it was perhaps just the wrong directory to run these commands, I entered the `go/src` directory and ran:

    mkdir -p bin
    mkdir -p mnist_mlp_cpu
    go build -o bin/mnist_mlp_cpu fragata/arhat/examples/mnist_mlp_cpu

Which gives this error message:

```
can't load package: package fragata/arhat/examples/mnist_mlp_cpu: cannot find package "fragata/arhat/examples/mnist_mlp_cpu" in any of:
/usr/lib/go/src/fragata/arhat/examples/mnist_mlp_cpu (from$GOROOT)
/home/afr/go/src/fragata/arhat/examples/mnist_mlp_cpu (from $GOPATH)
```

Variations of `go get -d` did not solve anything.

This is with Go 1.13.4 on Arch Linux (x86_64).

**Comment by lxgo** [comment]
There was an error in build instructions. Thank you for finding!

I fixed it and updated the repository now. Please try the updated version.

**Comment by xyproto** [comment]
It works now, after setting `GOPATH`. It's pretty cool that it generates `.cpp` files!

One suggestion to make it easier to use for Go developers would be to use the Go module system, for instance with something along the lines of:

    cd go/src/fragata/arhat
    go mod init github.com/fragata-ai/arhat

Then adjusting the import paths to start with "github.com/fragata-ai/arhat".

Many Go repositories have the Go source files together with `go.mod` in the top level directory, possibly together with a `vendor` directory (created with `go mod vendor`).
