### ISSUE TITLE
using Arhat with openvino

### ISSUE THREAD

**Issue by whyandra** [fragata-ai/arhat#2]
I found that the depository of arhat on GitHub was two years ago and was not updated, but I saw that the document was recently released. 
Do you maintain the arhat SDK elsewhere? 
At the same time, I saw "Pre-trained models can be imported from the external frameworks via bridge components supporting various exchange formats." in the document, but I didn't find the relevant knowledge([document](https://www.oneapi.io/event-sessions/using-arhat-framework-with-intel-onednn-library-and-openvino-toolkit-for-object-detection-applications/)). 
If it's convenient, can you tell me how to do this step? In the Arhat depository I can find, I also haven't found caffe2 related extensions. How can I find them?
I konw that detectron2 could be converted to openvino IR from this document，and I accomplished it. but when I want to combine it with Arhat,I didin't find how to get the openvino IR Bridge，could you please tell me how to do it?

**Comment by lxgo** [comment]
This repository contains results of our early experiments made prior to the definitive implementation of Arhat project. It is therefore not related to Arhat framework described in our more recent articles. To avoid possible confusion, we have recently renamed the project in this repository to Arhat Prequel and revised the description in README accordingly. The actual Arhat is a commercial product and its source code is currently not publicly available.
